# Launch the ShinyApp (Do not edit this file!)
pkgload::load_all(export_all = TRUE, helpers = FALSE, attach_testthat = FALSE)
options("golem.app.prod" = TRUE)
  golem::with_golem_options(
    app = shinyApp(
      ui = app_ui,
      server = app_server,
      onStart = NULL,
      options = list(),
      enableBookmarking = NULL,
      uiPattern = "/"
    ),
    golem_opts = list()
)
