name: Deploy to shinyapps.io

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (branch, tag, or SHA) to deploy'
        required: false
        default: ''

permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}

      - name: Install R toolchain
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'

      - name: Capture CRAN snapshot from R release date
        uses: ./.github/actions/capture-cran-snapshot

      - name: Configure CRAN snapshot
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'
          install-r: false
          cran: "${{ env.CRAN_SNAPSHOT }}"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rsconnect,any::desc
          cache: true
          cache-version: ubuntu-r-4-5-1

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: Rscript inst/tasks/deploy_to_shinyio.R
