# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at
# https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.5.1
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Capture CRAN snapshot from R release date
        uses: ./.github/actions/capture-cran-snapshot
      
      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          cran: "${{ env.CRAN_SNAPSHOT }}"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::roxygen2,any::rcmdcheck,any::desc
          cache: true
            
      - name: Build documentation with roxygen2
        run: roxygen2::roxygenise()
        shell: Rscript {0}
      
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual", "--no-build-vignettes")'
          args: 'c("--no-manual", "--as-cran", "--no-build-vignettes", "--ignore-vignettes")'

